project:
  type: website
  
website:
  title: "Ammu Lavanya"
  site-url: https://ammulavanya.github.io

  navbar:
    pinned: true
    collapse: true
    left: []        # keep empty so everything stays on the right
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching

  page-footer:
    left: "Â© Ammu Lavanya"
    right: ""
    
format:
  html:
    theme:
      - cosmo
      - styles.scss   # <-- use theme extension, not css:
    toc: false
    grid:
      body-width: "820px"
      margin-width: "0px"
      gutter-width: "24px"
    include-in-header:
      text: |
        <meta name="google-site-verification" content="k9VKEm2ukKgPvSGrvUOBCe4Yw_6_-czv341oPcGOG2g" />
